### PR TITLE
Album Artists in tables

### PR DESCRIPTION
**Pull request by randomnicode**

### CODE REVIEW

**Comment by The-Exterminator** [comment]
This table makes no sense as both the album and the artist are there.
Can you under "advanced" do one can turn it off

**Comment by randomnicode** [comment]
Artist != Album Artist != Album

Some albums are made by artists, but have guest or collaborating artists.

**Comment by randomnicode** [comment]
We can add a feature to turn it off

**Comment by The-Exterminator** [comment]
> We can add a feature to turn it off

You can made it Settings -> Personal ???

**Comment by The-Exterminator** [comment]
> Artist != Album Artist != Album
> 
> Some albums are made by artists, but have guest or collaborating artists. Or think of soundtracks where a song may be sung by someone, but they're only a collaborator, the credit for the album goes to the composer (who is the album artist).

I have a lot of album, nd all tags are from mp3tags and i have never see it :-(

**Comment by randomnicode** [comment]
It's a pretty standard ID3 tag.

**Comment by The-Exterminator** [comment]
> It's a pretty standard ID3 tag.

All my mp3 have Discogs and MusicBrainz tags, but the program is [mp3tags](https://www.mp3tag.de/en/)

**Pull request merged**
