### PR TITLE
Add support for cue-indexed files

### PR DESCRIPTION
**Pull request by Yetangitu**
This change adds support for cue-indexed files. Indexed tracks are added to the database using their relative position in the parent file and are played invidually by means of a "split" transcoding which is optionally inserted into the transcoding chain. Base files - the files from which tracks are indexed - are shown or hidden depending on whether the 'Hide cue-index files' option (on the Media Folders settings page) is set or not. Cue-indexed tracks are represented in the database by concatenating the base filename and the track start position within the base file, separated by a colon, e.g. /some/base/file.mp3:1234 indicates a track starting at 1234 seconds in file.mp3. The start position is stored in a new 'start_position' field in the database with a default value of '0'.

New settings:
Media Folders/Hide cue-indexed files (boolean): show (unset) or hide (set) cue-indexed base files
Transcoding/Split command (text): command used to split off section of a file for streaming, the default command `ffmpeg -ss %o -t %d -i %s -vcodec copy -acodec copy -f %f -` achieves this without transcoding.

This is a continuation of the cue-support patch I submitted to the original airsonic (https://github.com/airsonic/airsonic/pull/856) which never got merged (like many other PRs - the project seems to be stalled). This version has been refactored for airsonic-advanced and has some new changes related to the 'Hide cue-indexed files' option.

### CODE REVIEW

**Comment by Yetangitu** [comment]
> This pull request **introduces 1 alert** when merging [be4b30d](https://github.com/airsonic-advanced/airsonic-advanced/commit/be4b30dbd2d2c3498700b17d174ca79305ca893c) into [279b7c6](https://github.com/airsonic-advanced/airsonic-advanced/commit/279b7c613ed1435060a6bb1e138c575b55f6e4a1) - [view on LGTM.com](https://lgtm.com/projects/g/airsonic-advanced/airsonic-advanced/rev/pr-b7968c9579bf5fa6422973ec356d45621ef06712)
> 
> **new alerts:**
> 
>     * 1 for Potential input resource leak

Fixed in the most recent version

**Comment by randomnicode** [comment]
👀

**Comment by Yetangitu** [comment]
WRT to the way tracks are stored in the database I'd suggest it would be best to move from the current unique index on media_file.path to one on media_file.path+media_file.start_position. If that change were to be implemented the somewhat hacky way split tracks are represented - by adding the start time to the path, separated by a colon - could be dropped. Here's what I mean:

Current scheme:

```
airsonic=# select path,start_position from media_file where start_position <> 0 limit 10;
                                  path                                  | start_position 
------------------------------------------------------------------------+----------------
 /mnt/audio/music/Top_2000/2018/63-1200_1400_top_2000_20181230.mp3:5668 |           5668
 /mnt/audio/music/Top_2000/2018/41-1600_1800_top_2000_20181228.mp3:3447 |           3447
 /mnt/audio/music/Top_2000/2018/08-2200_0000_top_2000_20181225.mp3:4076 |           4076
 /mnt/audio/music/Top_2000/2018/38-1000_1200_top_2000_20181228.mp3:22   |             22
 /mnt/audio/music/Top_2000/2018/23-0400_0600_top_2000_20181227.mp3:4810 |           4810
 /mnt/audio/music/Top_2000/2020/Top_2000-20201225_15:00.mp3:540         |            540
 /mnt/audio/music/Top_2000/2018/52-1400_1600_top_2000_20181229.mp3:5218 |           5218
 /mnt/audio/music/Top_2000/2018/13-0800_1000_top_2000_20181226.mp3:5017 |           5017
 /mnt/audio/music/Top_2000/2018/25-0800_1000_top_2000_20181227.mp3:5513 |           5513
 /mnt/audio/music/Top_2000/2018/07-2000_2200_top_2000_20181225.mp3:1323 |           1323
(10 rows)

airsonic=# \d+ media_file;
...
 path                  | character varying           |           | not null |                                        | extended |              | 
 start_position        | integer                     |           |          | 0                                      | plain    |              | 
...
    "idx_media_file_path" UNIQUE, btree (path)

```

Proposed schema:

```
airsonic=# select path,start_position from media_file where start_position <> 0 limit 10;
                                  path                                  | start_position 
------------------------------------------------------------------------+----------------
 /mnt/audio/music/Top_2000/2018/63-1200_1400_top_2000_20181230.mp3      |           5668
 /mnt/audio/music/Top_2000/2018/41-1600_1800_top_2000_20181228.mp3      |           3447
 /mnt/audio/music/Top_2000/2018/08-2200_0000_top_2000_20181225.mp3      |           4076
 /mnt/audio/music/Top_2000/2018/38-1000_1200_top_2000_20181228.mp3      |             22
 /mnt/audio/music/Top_2000/2018/23-0400_0600_top_2000_20181227.mp3      |           4810
 /mnt/audio/music/Top_2000/2020/Top_2000-20201225_15:00.mp3             |            540
 /mnt/audio/music/Top_2000/2018/52-1400_1600_top_2000_20181229.mp3      |           5218
 /mnt/audio/music/Top_2000/2018/13-0800_1000_top_2000_20181226.mp3      |           5017
 /mnt/audio/music/Top_2000/2018/25-0800_1000_top_2000_20181227.mp3      |           5513
 /mnt/audio/music/Top_2000/2018/07-2000_2200_top_2000_20181225.mp3      |           1323
(10 rows)

airsonic=# \d+ media_file;
...
 path                  | character varying           |           | not null |                                        | extended |              | 
 start_position        | integer                     |           |          | 0                                      | plain    |              | 
...
    "idx_media_file_path_start_position" UNIQUE, btree (path,start_position)
```

This is already part of the change request but the change is disabled for now.

**Comment by carlox97** [comment]
> 👀

@randomnicode could you please look into adding cuesheet support?

**Comment by Yetangitu** [comment]
OK, I'll do some testing with an additional column once the relative-paths thing has been merged, after 3 years a few more weeks won't make a difference after all.

**Comment by Yetangitu** [comment]
With regard to the overloaded use of `media_file.path` in this change I've been doing some experiments. The `path` column is used all over _airsonic_  as a means to select a single track even though it is not the primary key for the table. This mostly works fine in the overloaded case [1] but it does not work if the overload construction is to be removed. To unambiguously identify a single track without using the primary key three columns are needed: `path`, `start_position` and `type` or `duration`. The last (`type`/`duration`) is needed to discern between indexed files and indexed tracks since both tend to have `start_position = 0`. Discerning between the two needs another field, the current solution [2] is to use `type` for this purpose with `MUSIC_INDEX_FILE` (which is optional) used to identify a file for which a CUE file is available and `MUSIC_INDEXED_TRACK` identifying sections of the former by means of the contents of the CUE file. Compared to the overloaded `path` column this is rather clunky so I'm looking for another solution, such as:

1. use the primary key `id` instead of `path`
2. create a stored synthetic key using `path` and `id`
3. add a `track` column which takes over the task of `path` as identifier for playable tracks. This `track` column is compound key, created from `path`, `start_position` and `type`. This goes against normalisation by adding redundant data but it makes it possible to keep the current code base mostly unchanged. Depending on the database the `track` column could be implemented as a generated column (e.g. Postgresql: `track character varying generated always as (path || ':' || start_position::text || ':' || type) stored, `, for Mysql replace `character varying` with `varchar(1024)` (or whatever size seems appropriate), HSQLDB only seems to support generated identity (i.e. serial) columns which seems to kill this idea on the spot given that HSQLDB is the default DB)
4. create a new table `media_track` (or something similar) which mostly looks like `media_file` with the following differences:
   - `start_position` is moved from `media_file` to `media_track`
   - all shared data - format, bit_rate, cover art etc - is only in `media_file`. Insertions and updates are done to the individual tables `media_file` and `media_track`, select queries are done over a view over these two tables using a compound key.

The first three options are clearly the least intrusive but lead to some duplication of data. The last option is the 'cleanest' but requires a bigger change. 

Given that the relative paths change seems to necessitate the use of the primary key (`id`) instead of `path` anyway I see this as the most viable option - agree?
___

1:

Only the `deleteMediaFile` and `deleteMediaFiles` calls are questionable since it is not possible to delete indexed tracks, it would however be possible to remove them from the database but this is currently not covered by this change set


```
2:

    public static enum MediaType {
        MUSIC,
        MUSIC_INDEXED_FILE,
        MUSIC_INDEXED_TRACK,
        PODCAST,
        AUDIOBOOK,
        AUDIOBOOK_INDEXED_FILE,
        AUDIOBOOK_INDEXED_TRACK,
        VIDEO,
        DIRECTORY,
        ALBUM,
        ALBUM_INDEXED_FILE;
...
...


3:

Table "public.media_file"
        Column         |            Type             | Nullable |                Default                 |
-----------------------+-----------------------------+----------+----------------------------------------+
 id                    | integer                     | not null | nextval('media_file_id_seq'::regclass) |
 path                  | character varying           | not null |                                        |
 folder                | character varying           |          |                                        |
 type                  | character varying           | not null |                                        |
 format                | character varying           |          |                                        |
 title                 | character varying           |          |                                        |
 album                 | character varying           |          |                                        |
 artist                | character varying           |          |                                        |
 album_artist          | character varying           |          |                                        |
 disc_number           | integer                     |          |                                        |
 track_number          | integer                     |          |                                        |
 year                  | integer                     |          |                                        |
 genre                 | character varying           |          |                                        |
 bit_rate              | integer                     |          |                                        |
 variable_bit_rate     | boolean                     | not null |                                        |
 file_size             | bigint                      |          |                                        |
 width                 | integer                     |          |                                        |
 height                | integer                     |          |                                        |
 cover_art_path        | character varying           |          |                                        |
 parent_path           | character varying           |          |                                        |
 play_count            | integer                     | not null |                                        |
 last_played           | timestamp without time zone |          |                                        |
 comment               | character varying           |          |                                        |
 created               | timestamp without time zone | not null |                                        |
 changed               | timestamp without time zone | not null |                                        |
 last_scanned          | timestamp without time zone | not null |                                        |
 children_last_updated | timestamp without time zone | not null |                                        |
 present               | boolean                     | not null |                                        |
 version               | integer                     | not null |                                        |
 mb_release_id         | character varying           |          |                                        |
 mb_recording_id       | character varying           |          |                                        |
 duration              | double precision            |          |                                        |
 duration_seconds      | integer                     |          | 0                                      |


Table "public.media_track"
        Column         |            Type             | Nullable |                Default                 |
-----------------------+-----------------------------+----------+----------------------------------------+
 id                    | integer                     | not null | nextval('media_track_id_seq'::regclass)|
 media_file_id         | integer                     | not null |                                        |
 title                 | character varying           |          |                                        |
 album                 | character varying           |          |                                        |
 artist                | character varying           |          |                                        |
 album_artist          | character varying           |          |                                        |
 disc_number           | integer                     |          |                                        |
 track_number          | integer                     |          |                                        |
 year                  | integer                     |          |                                        |
 genre                 | character varying           |          |                                        |
 play_count            | integer                     | not null |                                        |
 last_played           | timestamp without time zone |          |                                        |
 comment               | character varying           |          |                                        |
 mb_release_id         | character varying           |          |                                        |
 mb_recording_id       | character varying           |          |                                        |
 duration              | double precision            |          |                                        |
 start_position        | integer                     | mot null | 0                                      |

**Comment by Yetangitu** [comment]
A preview of the CUE-support change, rebased on the to-be-merged relative-paths change can be found in my repo:

https://github.com/Yetangitu/airsonic-advanced/tree/cue-support-with-relative-paths

**Comment by RuralHunter** [comment]
I have been using this PR since @Yetangitu submitted it to original airsonic like 3 years ago. There has been no problem at all.

**Comment by Yetangitu** [comment]
I'm waiting for the relative-paths change to be merged so I can push the new version to this PR. It does away with the somewhat hackish way indexed tracks are identified in the database, they're now identfied through a new start_position column (default -1.0 for "not indexed"). Splitting is now integrated into existing transcoders, this makes it work for formats like APE which FFMPEG can not split without transcoding and it has the added bonus of being more efficient. Formats which do not need transcoding still get handled by the split command like before. I have\ not created a migration routine yet, this will come once the relative-paths change has been merged.

If you feel like testing you can find the most recent version behind the link two posts up. Run it as a separate instance for now since it makes radical changes to the database scheme and I have not created a data migration routine yet - you'll need to rescan your library. The more testers, the better the results.

**Comment by Yetangitu** [comment]
This version of the PR is outdated, a new PR (#756) based on the recently-merged relativepaths change has been submitted.

**Review by Tesbarmix — APPROVED** [review]

**Pull request closed without merging**
