### PR TITLE
Use database-specific random function

### PR DESCRIPTION
**Pull request by Yetangitu**
Fix for #698, "Shuffle radio fails on PostgreSQL"; use a database-specific random function.

PostgreSQL uses `random()`, Mysql/MariaDB and HSQLDB use `rand()`, use `MetaData.getDatabaseProductName()` to check which DBMS is used and adjust the function name accordingly. This clause will still fail on e.g. SQL Server, Oracle and DB2 since these use totally different constructions [1] to select random rows. If these DBMS are to be supported the query needs to be restructured.

 [1]
 - SQL Server uses `SELECT TOP 1 column FROM table ORDER BY NEWID ();`
 - Oracle uses `SELECT column FROM (SELECT column FROM table ORDER BY dbms_random.value) WHERE rownum = 1;`
 - DB2 uses `SELECT column RAND () as IDX  FROM table ORDER BY  IDX FETCH FIRST 1 ROWS ONLY;`

### CODE REVIEW

**Comment by Yetangitu** [comment]
A simple alias would work for databases which differ only in the name of the random function - PostgreSQL and SQLite - but it will fail for other DBMS. I don't expect many installations using Oracle or DB2 but SQL Server is more wide-spread (the Express and Developer version are free to download and use). Should these be supported as well?

Otherwise this would work:

```sql
create or replace function rand () returns double precision language sql as $$
    select random()
$$;
```

**Comment by randomnicode** [comment]
i think until we have evidence people are using any of those, we can just make the change for postgres

**Comment by Yetangitu** [comment]
Not tested, should work

**Comment by randomnicode** [comment]
Can we add a test for the radio shuffle that exercises the rand() function?

**Comment by Yetangitu** [comment]
What would that test do? The only difference between PostgreSQL random() and MySQL rand() is the name. they both produce pseudo-random double precision (PostgreSQL) or "floating point" (MySQL, precision is machine-dependent) numbers between 0 and 1.

**Comment by randomnicode** [comment]
the test is at a higher level. the reason this bug went undetected was no one exercised that sql code in a test. testing that mediafileservice.getrandomsongs() does what it does would exercise the code

**Comment by randomnicode** [comment]
we'll merge this pr, but without a test we'll need someone to test with postgres in an actual prod code.

**Comment by Yetangitu** [comment]
That's me, I'm using PostgreSQL. It work. When I said "not tested" I meant I had not tested this specific version of the change since I've got a different build running which includes the previous iteration (with the "where" clause in the computedValue) and did not feel like building yet again with only that change. I tested the bare change in PostgreSQL, that works as well. Ergo, merge.

**Pull request merged**
